### PR TITLE
fix: prevent string input to be used in allocate function

### LINKED ISSUE #588: [Bug]: allocate() does not throw when given numeric strings as input
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

First off, thanks for the great library.

.allocate() function has unexpected behaviour when given falsy input.

### Expected behavior

I expected an error:
`` TypeError: You must provide a non-empty array of numeric values greater than 0 ``

### Steps to reproduce

```
try {
    Dinero({ amount: 100 })
    .allocate([ '2', '98' ])
} catch (error) {
    console.log(error)
}
```

It never finishes nor throws meanwhile hogging memory.

The same for this:
``.allocate([ 1, '98' ])``

But this one yields the expected TypeError:
``.allocate([ 'a', '98' ])``

### Version

1.9.1

### Environment

14.17.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by matheusfcorocher**
## How was it solved?
It was fixed by adding a condition that verifies if ratio is numeric and has number type in areValidRatios function. 

fixes #588

### CODE REVIEW

File: src/services/helpers.js [hunk 1]
```diff
@@ -33,6 +33,7 @@ export function isPercentage(percentage) {
 export function areValidRatios(ratios) {
   return (
     ratios.length > 0 &&
+    ratios.every(ratio => typeof ratio === 'number' && isNumeric(ratio)) &&
     ratios.every(ratio => ratio >= 0) &&
```
Comment (sarahdayan) [inline src/services/helpers.js:37]: We can combine these two to avoid traversing the whole array twice.

File: test/unit/dinero.spec.js [hunk 2]
```diff
@@ -277,6 +277,10 @@ describe('Dinero', () => {
       const shares = Dinero({ amount: 1003 }).allocate([0, 50, 50])
       expect(shares.map(share => share.getAmount())).toEqual([0, 502, 501])
     })
+    test('should allocate the amount of the Dinero object into new ones and distribute the remainder when one of ratios is float number', () => {
+      const shares = Dinero({ amount: 1000 }).allocate([1.618, 1])
+      expect(shares.map(share => share.getAmount())).toEqual([619, 381])
+    })
```
Comment (sarahdayan) [inline test/unit/dinero.spec.js:283]: This seems unrelated to the PR's objective.

**Review by sarahdayan — APPROVED** [review]

**Comment by sarahdayan** [comment]
Thanks @matheusfcorocher!
