### PR TITLE
fix(toDecimal): preserve negative sign for leading zeros

### LINKED ISSUE #692: [Bug]: toDecimal fails to print a leading negative sign when the first unit is negative zero
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

#690 fixed the the general case of formatting negative unit values, but there is one outstanding specific case where formatting is still incorrect: when the first unit is -0, the resulting string doesn't include the leading negative sign.

This occurs because the (default) `toString` formatter is `String`, and `String(-0)` produces `'0'`.

```ts
toDecimal(dinero({ amount: -1, currency: USD }) === '0.01'
```

### Expected behavior

```ts
toDecimal(dinero({ amount: -1, currency: USD }) === '-0.01'
```

### Steps to reproduce

Here's a failing test case:

```ts
it('returns the negative amount for the last unit in decimal format', () => {
  const d = dinero({ amount: -1, currency: USD });

  expect(toDecimal(d)).toEqual('-0.01');
});
```
```
Expected: "-0.01"
Received: "0.01"
```

### Version

2.0.0-alpha12

### Environment

Node.js 16.14.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jparise**
Change #690 fixed the general case of formatting negative unit values, but was one remaining case where formatting was still incorrect: when the first unit is -0, the resulting string didn't include the leading negative sign.

This change identifies that exact case (negative value, leading zero) and pads the resulting string with a leading negative sign.

Fixes #692

### CODE REVIEW

File: packages/core/src/api/toDecimal.ts [hunk 1]
```diff
@@ -32,9 +41,15 @@ export function toDecimal<TAmount, TOutput>(calculator: Calculator<TAmount>) {
...
+    const isNegative = units.some((unit) => lessThanFn(signFn(unit), zero));
 
     const getDecimalFn = getDecimal(calculator, dineroObject.formatter);
-    const value = getDecimalFn(units, scale);
+    const decimalValue = getDecimalFn(units, scale);
+
+    // A leading negative zero is a special case because the toString
+    // formatter (generally String) won't preserve its negative sign.
+    const value =
+      isNegative && equalFn(units[0], zero) ? `-${decimalValue}` : decimalValue;
```
Comment (jparise) [inline packages/core/src/api/toDecimal.ts:52]: I could also use `isZero` here, but we already have all of the components at hand to perform this check. Let me know if `isZero` is preferred.

File: packages/core/src/api/toDecimal.ts [hunk 2]
```diff
@@ -32,9 +41,15 @@ export function toDecimal<TAmount, TOutput>(calculator: Calculator<TAmount>) {
     assert(isDecimal, NON_DECIMAL_CURRENCY_MESSAGE);
 
     const units = toUnitsFn(dineroObject);
+    const isNegative = units.some((unit) => lessThanFn(signFn(unit), zero));
```
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:44]: We should be able to simplify this further and not even have to map over units (either here or even reusing the existing `Array.map` in `getDecimal`).

Normally, when using `toUnits` with a decimal Dinero objects (base 10 with a single base) it should always return a tuple of 2.

```js
toUnits(dinero({ amount: -1, currency: USD })) // [-0, -1]
toUnits(dinero({ amount: -0, currency: USD })) // [-0, -0]
```

If the first unit is zero, then we can just test the second unit for being negative instead of mapping over all units. This way, the second test only happens when necessary (when the first unit is zero) and we avoid an unnecessary iteration.

File: packages/core/src/api/toDecimal.ts (hunk 1 above)
Comment (sarahdayan) [reply packages/core/src/api/toDecimal.ts:52]: Importing `isZero` might make `toDecimal` slightly heavier, so I prefer your approach.

File: packages/core/src/api/toDecimal.ts (hunk 2 above)
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:44]: Not sure you need `sign`. Comparing `unit` against `zero` should already work.

File: packages/core/src/api/toDecimal.ts [hunk 3]
```diff
@@ -32,9 +41,15 @@ export function toDecimal<TAmount, TOutput>(calculator: Calculator<TAmount>) {
...
 
     const getDecimalFn = getDecimal(calculator, dineroObject.formatter);
-    const value = getDecimalFn(units, scale);
+    const decimalValue = getDecimalFn(units, scale);
```
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:47]: I would probably perform the two checks (whether it leads with zero and is negative) inside `getDecimal`—I expect this function to return the correct value. wdyt?

File: packages/core/src/api/toDecimal.ts (hunk 2 above)
Comment (jparise) [reply packages/core/src/api/toDecimal.ts]: Yes, that makes good sense. Can we always assume there's a second value in the tuple? I used `units.length - 1` just in case that's not always the case.

Comment (jparise) [reply packages/core/src/api/toDecimal.ts]: Yes, this looks pretty funny in hindsight! I started with `sign`, then realized it returns a `TAmount` value, and then introduced the `lessThan` check to handle it. 😄

File: packages/core/src/api/toDecimal.ts [hunk 4]
```diff
@@ -49,12 +49,17 @@ function getDecimal<TAmount>(
...
 
   return (units: readonly TAmount[], scale: TAmount) => {
-    return units
+    const lastIndex = units.length - 1;
+
+    const decimalString = units
       .map((unit, index) => {
         const isFirst = index === 0;
-        const isLast = units.length - 1 === index;
+        const isLast = lastIndex === index;
```
Comment (jparise) [inline packages/core/src/api/toDecimal.ts:62]: I think we could also drop `isFirst` and `isLast` in favor of comparing directly to `index` in the following lines. `index === 0` and `index === lastIndex` are pretty self-descriptive. I don't know if using constants is more v8-friendly, though.

File: packages/core/src/api/toDecimal.ts (hunk 2 above)
Comment (sarahdayan) [reply packages/core/src/api/toDecimal.ts]: When wasn't it the case? With decimal objects it should be.

File: packages/core/src/api/toDecimal.ts (hunk 4 above)
Comment (sarahdayan) [reply packages/core/src/api/toDecimal.ts:62]: I'm fine with inlining as long as it doesn't hurt readability, as the performance gains are usually very small.

If you think that works well here, go for it.

**Comment by jparise** [comment]
Given that `getDecimal` always receives a two-element `units` array, I took a more "drastic" approach and unrolled the `.map()` operation. We were specializing each element (first, last) within the mapping function anyway.

(`getDecimal` could `assert(units.length === 2, ...)`, but I think the `assert()` in `toDecimal` already covers this "must be decimal" case?)

I think this results in a simpler solution overall that only uses a single top-level branch (to determine if we need to add the leading negative).

File: packages/core/src/api/toDecimal.ts [hunk 5]
```diff
@@ -49,23 +49,22 @@ function getDecimal<TAmount>(
...
-        );
-
-        if (isLast) {
-          return unitAsString.padStart(formatter.toNumber(scale), '0');
-        }
-
-        return unitAsString;
-      })
-      .join('.');
+    const integer = formatter.toString(units[0]);
```
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:57]:
```suggestion
    const whole = formatter.toString(units[0]);
```

File: packages/core/src/api/toDecimal.ts [hunk 6]
```diff
@@ -49,23 +49,22 @@ function getDecimal<TAmount>(
...
+    const fractional = formatter.toString(absoluteFn(units[1]));
+
+    const scaleNumber = formatter.toNumber(scale);
+    const decimal = `${integer}.${fractional.padStart(scaleNumber, '0')}`;
```
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:61]:
```suggestion
    const decimal = `${whole}.${fractional.padStart(scaleNumber, '0')}`;
```

File: packages/core/src/api/toDecimal.ts [hunk 7]
```diff
@@ -49,23 +49,22 @@ function getDecimal<TAmount>(
...
+
+    // A leading negative zero is a special case because the toString
+    // formatter (generally String) won't preserve its negative sign.
```
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:64]:
```suggestion
```

File: packages/core/src/api/toDecimal.ts [hunk 8]
```diff
@@ -49,23 +49,22 @@ function getDecimal<TAmount>(
...
+    const leadsWithZero = equalFn(units[0], zero);
+    const isNegative = lessThanFn(units[1], zero);
+
+    return leadsWithZero && isNegative ? `-${decimal}` : decimal;
```
Comment (sarahdayan) [inline packages/core/src/api/toDecimal.ts:68]:
```suggestion
    // A leading negative zero is a special case because the `toString`
    // formatter won't preserve its negative sign (since 0 === -0).
    return leadsWithZero && isNegative ? `-${decimal}` : decimal;
```

**Review by sarahdayan — COMMENTED** [review]
Excellent rewrite! A few suggestions and we'll be good to go.

**Review by sarahdayan — APPROVED** [review]
Awesome contribution, thanks @jparise!
